openapi: 3.1.0
info:
  title: "NEAR Protocol RPC: Get light client block proof"
  description: "Fetch a Merkle proof that a block is included in the light client's verified chain."
  version: 1.0.0
servers:
  - url: "https://rpc.mainnet.fastnear.com"
    description: Mainnet
  - url: "https://rpc.testnet.fastnear.com"
    description: Testnet
paths:
  /:
    post:
      operationId: EXPERIMENTAL_light_client_block_proof
      summary: Get light client block proof
      description: "Fetch a Merkle proof that a block is included in the light client's verified chain."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [jsonrpc, id, method, params]
              properties:
                jsonrpc:
                  type: string
                  enum: ["2.0"]
                id:
                  type: string
                  example: fastnear
                method:
                  type: string
                  enum: [EXPERIMENTAL_light_client_block_proof]
                params:
                  type: object
                  properties:
                    block_hash:
                      type: string
                      description: Base58-encoded hash
                    light_client_head:
                      type: string
                      description: Base58-encoded hash
                  required: [block_hash, light_client_head]
            examples:
              mainnet:
                summary: Get light client block proof (Mainnet)
                value:
                  jsonrpc: "2.0"
                  id: fastnear
                  method: EXPERIMENTAL_light_client_block_proof
                  params:
                    block_hash: 8fbT7nWhBwsBJjPcwhv2uqzseFJSd5Y4XcqfLAWryBsu
                    light_client_head: 6sddgq8nkENAz4f8qR72qxRPM25QWNBVMrkYr63DgC2E
              testnet:
                summary: Get light client block proof (Testnet)
                value:
                  jsonrpc: "2.0"
                  id: fastnear
                  method: EXPERIMENTAL_light_client_block_proof
                  params:
                    block_hash: 6MSNnEmewGXHVCbW6hSqNRgptByQbfyrvQJyho88EM1A
                    light_client_head: Ayfw9wu3T3zEqCbrvq9CuKmGmuyiJiETvwCApXZHmCho
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonRpcResponse"
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: apiKey
  schemas:
    JsonRpcResponse:
      type: object
      required: [jsonrpc, id]
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        id:
          oneOf:
            - type: string
            - type: number
        result:
          type: object
          properties:
            block_header_lite:
              type: object
              properties:
                inner_lite:
                  type: object
                  description: "A part of a state for the current head of a light client. More info [here](https://nomicon.io/ChainSpec/LightClient)."
                inner_rest_hash:
                  type: string
                  description: Base58-encoded hash
                prev_block_hash:
                  type: string
                  description: Base58-encoded hash
              required: [prev_block_hash, inner_rest_hash, inner_lite]
            block_proof:
              type: array
              items:
                type: object
          required: [block_header_lite, block_proof]
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
            data:
              type: object
