/* This file is auto-generated by scripts/generate-page-models.js. */
/* Do not edit it by hand; regenerate it via npm run sync:apis or npm run standalone:build. */

import structuredGraph from "./generatedFastnearStructuredGraph.json";

export const FASTNEAR_STRUCTURED_GRAPH = structuredGraph;

export type GeneratedFastnearStructuredGraph = typeof FASTNEAR_STRUCTURED_GRAPH;
