/* This file is auto-generated by scripts/sync-external-apis.js. */
/* Do not edit it by hand; update the portal-owned manifests in enhancements/<service>/manifest.yaml instead. */

export const DOCS_ENHANCEMENTS = {
  "fastnear": {
    "service": "fastnear",
    "pathPrefix": "/apis/fastnear/",
    "operations": {
      "/apis/fastnear/system/health": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-system-health",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/system/health.yaml",
          "operationRoute": "/apis/fastnear/openapi/system/get_health"
        }
      },
      "/apis/fastnear/system/status": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-system-status",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/system/status.yaml",
          "operationRoute": "/apis/fastnear/openapi/system/get_status"
        }
      },
      "/apis/fastnear/v0/account_staking": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v0-account-staking",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v0/account_staking.yaml",
          "operationRoute": "/apis/fastnear/openapi/staking/account_staking_v0"
        },
        "defaults": {
          "preset": "ecosystem-account"
        },
        "presets": {
          "ecosystem-account": {
            "path": {
              "account_id": {
                "mainnet": "root.near",
                "testnet": "root.testnet"
              }
            }
          }
        }
      },
      "/apis/fastnear/v0/account_ft": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v0-account-ft",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v0/account_ft.yaml",
          "operationRoute": "/apis/fastnear/openapi/fungible-tokens/account_ft_v0"
        },
        "defaults": {
          "preset": "ecosystem-account"
        },
        "presets": {
          "ecosystem-account": {
            "path": {
              "account_id": {
                "mainnet": "root.near",
                "testnet": "root.testnet"
              }
            }
          }
        }
      },
      "/apis/fastnear/v0/account_nft": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v0-account-nft",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v0/account_nft.yaml",
          "operationRoute": "/apis/fastnear/openapi/non-fungible-tokens/account_nft_v0"
        },
        "defaults": {
          "preset": "ecosystem-account"
        },
        "presets": {
          "ecosystem-account": {
            "path": {
              "account_id": {
                "mainnet": "root.near",
                "testnet": "root.testnet"
              }
            }
          }
        }
      },
      "/apis/fastnear/v0/public_key_lookup": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v0-public-key-lookup",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v0/public_key_lookup.yaml",
          "operationRoute": "/apis/fastnear/openapi/public-key/lookup_by_public_key_v0"
        },
        "defaults": {
          "preset": "root-access-key"
        },
        "presets": {
          "root-access-key": {
            "path": {
              "public_key": {
                "mainnet": "ed25519:CCaThr3uokqnUs6Z5vVnaDcJdrfuTpYJHJWcAGubDjT",
                "testnet": "ed25519:5FiU4tWnA2QmivpLTdHJhLeSfeZ7KuW4KKNaDqoBKue2"
              }
            }
          }
        }
      },
      "/apis/fastnear/v0/public_key_lookup_all": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v0-public-key-lookup-all",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v0/public_key_lookup_all.yaml",
          "operationRoute": "/apis/fastnear/openapi/public-key/lookup_by_public_key_all_v0"
        },
        "defaults": {
          "preset": "root-access-key"
        },
        "presets": {
          "root-access-key": {
            "path": {
              "public_key": {
                "mainnet": "ed25519:CCaThr3uokqnUs6Z5vVnaDcJdrfuTpYJHJWcAGubDjT",
                "testnet": "ed25519:5FiU4tWnA2QmivpLTdHJhLeSfeZ7KuW4KKNaDqoBKue2"
              }
            }
          }
        }
      },
      "/apis/fastnear/v1/account_staking": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v1-account-staking",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v1/account_staking.yaml",
          "operationRoute": "/apis/fastnear/openapi/staking/account_staking_v1"
        },
        "defaults": {
          "preset": "ecosystem-account"
        },
        "presets": {
          "ecosystem-account": {
            "path": {
              "account_id": {
                "mainnet": "root.near",
                "testnet": "root.testnet"
              }
            }
          }
        }
      },
      "/apis/fastnear/v1/account_ft": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v1-account-ft",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v1/account_ft.yaml",
          "operationRoute": "/apis/fastnear/openapi/fungible-tokens/account_ft_v1"
        },
        "defaults": {
          "preset": "ecosystem-account"
        },
        "presets": {
          "ecosystem-account": {
            "path": {
              "account_id": {
                "mainnet": "root.near",
                "testnet": "root.testnet"
              }
            }
          }
        }
      },
      "/apis/fastnear/v1/account_nft": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v1-account-nft",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v1/account_nft.yaml",
          "operationRoute": "/apis/fastnear/openapi/non-fungible-tokens/account_nft_v1"
        },
        "defaults": {
          "preset": "ecosystem-account"
        },
        "presets": {
          "ecosystem-account": {
            "path": {
              "account_id": {
                "mainnet": "root.near",
                "testnet": "root.testnet"
              }
            }
          }
        }
      },
      "/apis/fastnear/v1/account_full": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v1-account-full",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v1/account_full.yaml",
          "operationRoute": "/apis/fastnear/openapi/accounts/account_full_v1"
        },
        "defaults": {
          "preset": "ecosystem-account"
        },
        "presets": {
          "ecosystem-account": {
            "path": {
              "account_id": {
                "mainnet": "root.near",
                "testnet": "root.testnet"
              }
            }
          }
        }
      },
      "/apis/fastnear/v1/public_key_lookup": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v1-public-key-lookup",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v1/public_key_lookup.yaml",
          "operationRoute": "/apis/fastnear/openapi/public-key/lookup_by_public_key_v1"
        },
        "defaults": {
          "preset": "root-access-key"
        },
        "presets": {
          "root-access-key": {
            "path": {
              "public_key": {
                "mainnet": "ed25519:CCaThr3uokqnUs6Z5vVnaDcJdrfuTpYJHJWcAGubDjT",
                "testnet": "ed25519:5FiU4tWnA2QmivpLTdHJhLeSfeZ7KuW4KKNaDqoBKue2"
              }
            }
          }
        }
      },
      "/apis/fastnear/v1/ft_top": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v1-ft-top",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v1/ft_top.yaml",
          "operationRoute": "/apis/fastnear/openapi/fungible-tokens/ft_top_v1"
        },
        "defaults": {
          "preset": "wrapped-near"
        },
        "presets": {
          "wrapped-near": {
            "path": {
              "token_id": {
                "mainnet": "wrap.near",
                "testnet": "wrap.testnet"
              }
            }
          }
        }
      },
      "/apis/fastnear/v1/public_key_lookup_all": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "fastnear-v1-public-key-lookup-all",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/fastnear/v1/public_key_lookup_all.yaml",
          "operationRoute": "/apis/fastnear/openapi/public-key/lookup_by_public_key_all_v1"
        },
        "defaults": {
          "preset": "root-access-key"
        },
        "presets": {
          "root-access-key": {
            "path": {
              "public_key": {
                "mainnet": "ed25519:CCaThr3uokqnUs6Z5vVnaDcJdrfuTpYJHJWcAGubDjT",
                "testnet": "ed25519:5FiU4tWnA2QmivpLTdHJhLeSfeZ7KuW4KKNaDqoBKue2"
              }
            }
          }
        }
      }
    }
  },
  "kv-fastdata": {
    "service": "kv-fastdata",
    "pathPrefix": "/apis/kv-fastdata/",
    "operations": {
      "/apis/kv-fastdata/v0/all_by_predecessor": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "kv-fastdata-v0-all-by-predecessor",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/all_by_predecessor.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/latest/all_by_predecessor"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "predecessor-latest"
        },
        "presets": {
          "predecessor-latest": {
            "path": {
              "predecessor_id": {
                "mainnet": "james.near",
                "testnet": "kv.gork-agent.testnet"
              }
            },
            "body": {
              "include_metadata": true,
              "limit": 50
            }
          }
        }
      },
      "/apis/kv-fastdata/v0/history_by_key": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "kv-fastdata-v0-history-by-key",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/history_by_key.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/history/history_by_key"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "global-key-history"
        },
        "presets": {
          "global-key-history": {
            "bodyByNetwork": {
              "mainnet": {
                "asc": true,
                "include_metadata": false,
                "key": "graph/follow/sleet.near",
                "limit": 50
              },
              "testnet": {
                "asc": false,
                "include_metadata": false,
                "key": "value",
                "limit": 50
              }
            }
          }
        }
      },
      "/apis/kv-fastdata/v0/history_by_account": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "kv-fastdata-v0-history-by-account",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/history_by_account.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/history/history_by_account"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "account-history"
        },
        "presets": {
          "account-history": {
            "path": {
              "current_account_id": {
                "mainnet": "social.near",
                "testnet": "kv.gork-agent.testnet"
              }
            },
            "bodyByNetwork": {
              "mainnet": {
                "asc": true,
                "include_metadata": true,
                "key_prefix": "graph/follow/sleet.near",
                "limit": 10
              },
              "testnet": {
                "asc": false,
                "include_metadata": true,
                "key_prefix": "value",
                "limit": 50
              }
            }
          }
        }
      },
      "/apis/kv-fastdata/v0/history_by_predecessor": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "kv-fastdata-v0-history-by-predecessor",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/history_by_predecessor.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/history/history_by_predecessor"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "predecessor-history"
        },
        "presets": {
          "predecessor-history": {
            "path": {
              "current_account_id": {
                "mainnet": "social.near",
                "testnet": "kv.gork-agent.testnet"
              },
              "predecessor_id": {
                "mainnet": "james.near",
                "testnet": "kv.gork-agent.testnet"
              }
            },
            "bodyByNetwork": {
              "mainnet": {
                "asc": false,
                "include_metadata": true,
                "key_prefix": "graph/follow/",
                "limit": 50
              },
              "testnet": {
                "asc": false,
                "include_metadata": true,
                "key_prefix": "value",
                "limit": 50
              }
            }
          }
        }
      },
      "/apis/kv-fastdata/v0/get_history_key": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "kv-fastdata-v0-get-history-key",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/get_history_key.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/history/get_history_key"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "exact-history-key"
        },
        "presets": {
          "exact-history-key": {
            "path": {
              "current_account_id": {
                "mainnet": "social.near",
                "testnet": "kv.gork-agent.testnet"
              },
              "predecessor_id": {
                "mainnet": "james.near",
                "testnet": "kv.gork-agent.testnet"
              },
              "key": {
                "mainnet": "graph/follow/sleet.near",
                "testnet": "value"
              }
            }
          }
        }
      },
      "/apis/kv-fastdata/v0/latest_by_account": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "kv-fastdata-v0-latest-by-account",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/latest_by_account.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/latest/latest_by_account"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "account-latest"
        },
        "presets": {
          "account-latest": {
            "path": {
              "current_account_id": {
                "mainnet": "social.near",
                "testnet": "kv.gork-agent.testnet"
              }
            },
            "bodyByNetwork": {
              "mainnet": {
                "include_metadata": true,
                "key_prefix": "graph/follow/",
                "limit": 50
              },
              "testnet": {
                "include_metadata": true,
                "key_prefix": "value",
                "limit": 50
              }
            }
          }
        }
      },
      "/apis/kv-fastdata/v0/latest_by_predecessor": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "kv-fastdata-v0-latest-by-predecessor",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/latest_by_predecessor.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/latest/latest_by_predecessor"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "predecessor-latest-contract"
        },
        "presets": {
          "predecessor-latest-contract": {
            "path": {
              "current_account_id": {
                "mainnet": "social.near",
                "testnet": "kv.gork-agent.testnet"
              },
              "predecessor_id": {
                "mainnet": "james.near",
                "testnet": "kv.gork-agent.testnet"
              }
            },
            "bodyByNetwork": {
              "mainnet": {
                "include_metadata": true,
                "key_prefix": "graph/follow/",
                "limit": 50
              },
              "testnet": {
                "include_metadata": true,
                "key_prefix": "value",
                "limit": 50
              }
            }
          }
        }
      },
      "/apis/kv-fastdata/v0/get_latest_key": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "kv-fastdata-v0-get-latest-key",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/get_latest_key.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/latest/get_latest_key"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "exact-latest-key"
        },
        "presets": {
          "exact-latest-key": {
            "path": {
              "current_account_id": {
                "mainnet": "social.near",
                "testnet": "kv.gork-agent.testnet"
              },
              "predecessor_id": {
                "mainnet": "james.near",
                "testnet": "kv.gork-agent.testnet"
              },
              "key": {
                "mainnet": "graph/follow/sleet.near",
                "testnet": "value"
              }
            }
          }
        }
      },
      "/apis/kv-fastdata/v0/multi": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "kv-fastdata-v0-multi",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/kv-fastdata/v0/multi.yaml",
          "operationRoute": "/apis/kv-fastdata/openapi/latest/multi"
        },
        "defaults": {
          "network": "mainnet",
          "preset": "multi-settings"
        },
        "presets": {
          "multi-settings": {
            "bodyByNetwork": {
              "mainnet": {
                "include_metadata": true,
                "keys": [
                  "social.near/james.near/graph/follow/sleet.near",
                  "social.near/james.near/graph/follow/missing"
                ]
              },
              "testnet": {
                "include_metadata": true,
                "keys": [
                  "kv.gork-agent.testnet/kv.gork-agent.testnet/value",
                  "kv.gork-agent.testnet/kv.gork-agent.testnet/missing"
                ]
              }
            }
          }
        }
      }
    }
  },
  "neardata": {
    "service": "neardata",
    "pathPrefix": "/apis/neardata/",
    "operations": {
      "/apis/neardata/system/health": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-system-health",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/system/health.yaml",
          "operationRoute": "/apis/neardata/openapi/system/get_health"
        },
        "defaults": {
          "network": "mainnet"
        }
      },
      "/apis/neardata/v0/first_block": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-v0-first-block",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/v0/first_block.yaml",
          "operationRoute": "/apis/neardata/openapi/blocks/get_first_block"
        },
        "defaults": {
          "network": "mainnet"
        }
      },
      "/apis/neardata/v0/block": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-v0-block",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/v0/block.yaml",
          "operationRoute": "/apis/neardata/openapi/blocks/get_block"
        },
        "defaults": {
          "preset": "genesis",
          "network": "mainnet"
        },
        "presets": {
          "genesis": {
            "path": {
              "block_height": {
                "mainnet": "9820210",
                "testnet": "42376888"
              }
            }
          }
        }
      },
      "/apis/neardata/v0/block_headers": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-v0-block-headers",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/v0/block_headers.yaml",
          "operationRoute": "/apis/neardata/openapi/blocks/get_block_headers"
        },
        "defaults": {
          "preset": "genesis",
          "network": "mainnet"
        },
        "presets": {
          "genesis": {
            "path": {
              "block_height": {
                "mainnet": "9820210",
                "testnet": "42376888"
              }
            }
          }
        }
      },
      "/apis/neardata/v0/block_chunk": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-v0-block-chunk",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/v0/block_chunk.yaml",
          "operationRoute": "/apis/neardata/openapi/blocks/get_chunk"
        },
        "defaults": {
          "preset": "genesis-chunk",
          "network": "mainnet"
        },
        "presets": {
          "genesis-chunk": {
            "path": {
              "block_height": {
                "mainnet": "50000000",
                "testnet": "42376888"
              },
              "shard_id": {
                "default": "0"
              }
            }
          }
        }
      },
      "/apis/neardata/v0/block_shard": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-v0-block-shard",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/v0/block_shard.yaml",
          "operationRoute": "/apis/neardata/openapi/blocks/get_shard"
        },
        "defaults": {
          "preset": "genesis-shard",
          "network": "mainnet"
        },
        "presets": {
          "genesis-shard": {
            "path": {
              "block_height": {
                "mainnet": "50000000",
                "testnet": "42376888"
              },
              "shard_id": {
                "default": "0"
              }
            }
          }
        }
      },
      "/apis/neardata/v0/block_optimistic": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-v0-block-optimistic",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/v0/block_optimistic.yaml",
          "operationRoute": "/apis/neardata/openapi/blocks/get_block_optimistic"
        },
        "defaults": {
          "preset": "genesis",
          "network": "mainnet"
        },
        "presets": {
          "genesis": {
            "path": {
              "block_height": {
                "mainnet": "9820210",
                "testnet": "42376888"
              }
            }
          }
        }
      },
      "/apis/neardata/v0/last_block_final": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-v0-last-block-final",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/v0/last_block_final.yaml",
          "operationRoute": "/apis/neardata/openapi/blocks/get_last_block_final"
        },
        "defaults": {
          "network": "mainnet"
        }
      },
      "/apis/neardata/v0/last_block_optimistic": {
        "customPage": {
          "kind": "fastnear-rest-read",
          "pageModelId": "neardata-v0-last-block-optimistic",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/neardata/v0/last_block_optimistic.yaml",
          "operationRoute": "/apis/neardata/openapi/blocks/get_last_block_optimistic"
        },
        "defaults": {
          "network": "mainnet"
        }
      }
    }
  },
  "transactions": {
    "service": "transactions",
    "pathPrefix": "/apis/transactions/",
    "operations": {
      "/apis/transactions/v0/account": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "transactions-v0-account",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/transactions/v0/account.yaml",
          "operationRoute": "/apis/transactions/openapi/account/get_account"
        },
        "defaults": {
          "preset": "recent-account-history"
        },
        "presets": {
          "recent-account-history": {
            "body": {
              "desc": true,
              "is_real_signer": true,
              "is_success": true,
              "limit": 50
            },
            "bodyByNetwork": {
              "mainnet": {
                "account_id": "intents.near"
              },
              "testnet": {
                "account_id": "root.testnet"
              }
            }
          }
        }
      },
      "/apis/transactions/v0/block": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "transactions-v0-block",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/transactions/v0/block.yaml",
          "operationRoute": "/apis/transactions/openapi/blocks/get_block"
        },
        "defaults": {
          "preset": "expanded-block"
        },
        "presets": {
          "expanded-block": {
            "body": {
              "with_receipts": true,
              "with_transactions": true
            },
            "bodyByNetwork": {
              "mainnet": {
                "block_id": 193916411
              },
              "testnet": {
                "block_id": 46562457
              }
            }
          }
        }
      },
      "/apis/transactions/v0/blocks": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "transactions-v0-blocks",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/transactions/v0/blocks.yaml",
          "operationRoute": "/apis/transactions/openapi/blocks/get_blocks"
        },
        "defaults": {
          "preset": "recent-block-range"
        },
        "presets": {
          "recent-block-range": {
            "body": {
              "desc": false,
              "limit": 10
            },
            "bodyByNetwork": {
              "mainnet": {
                "from_block_height": 193916402,
                "to_block_height": 193916411
              },
              "testnet": {
                "from_block_height": 46562448,
                "to_block_height": 46562457
              }
            }
          }
        }
      },
      "/apis/transactions/v0/receipt": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "transactions-v0-receipt",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/transactions/v0/receipt.yaml",
          "operationRoute": "/apis/transactions/openapi/receipts/get_receipt"
        },
        "defaults": {
          "preset": "receipt-lookup"
        },
        "presets": {
          "receipt-lookup": {
            "bodyByNetwork": {
              "mainnet": {
                "receipt_id": "gzqDSvd3ZMcVUWzBMP7j9KMWz89iZMkkEvW9g8QZjUP"
              },
              "testnet": {
                "receipt_id": "8D3YiLcKYLAeNYmshj9cVwCTX6mgeWNXux4sJQ7FUTvV"
              }
            }
          }
        }
      },
      "/apis/transactions/v0/transactions": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "transactions-v0-transactions",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/transactions/v0/transactions.yaml",
          "operationRoute": "/apis/transactions/openapi/transactions/get_transactions"
        },
        "defaults": {
          "preset": "transaction-hash-pair"
        },
        "presets": {
          "transaction-hash-pair": {
            "bodyByNetwork": {
              "mainnet": {
                "tx_hashes": [
                  "FDrh13CdfGPXsmwUpZLfkZCoXWfpQmaFGj4zYWc1qfh",
                  "Eq1a46bynaBAjoSxd2XGWdCxkZdrMvN9jMZVdZfPSjM5"
                ]
              },
              "testnet": {
                "tx_hashes": [
                  "Cb9GXbQVodeJsVLiK2YnBR28vkiD7y4pEFGhxMGuP33q",
                  "9ufyhaEEzmerQz1Fvt2N91ZwXCcNZVhJXhq3QzRJZgfW"
                ]
              }
            }
          }
        }
      }
    }
  },
  "transfers": {
    "service": "transfers",
    "pathPrefix": "/apis/transfers/",
    "operations": {
      "/apis/transfers/v0/transfers": {
        "customPage": {
          "kind": "fastnear-rest-body",
          "pageModelId": "transfers-v0-transfers",
          "replaceOperationPage": true,
          "authTransport": "bearer",
          "sourceSpec": "apis/transfers/v0/transfers.yaml",
          "operationRoute": "/apis/transfers/openapi/transfers/get_transfers_by_account"
        },
        "defaults": {
          "preset": "recent-near-transfers"
        },
        "presets": {
          "recent-near-transfers": {
            "body": {
              "account_id": "root.near",
              "desc": true,
              "limit": 10
            }
          }
        }
      }
    }
  }
} as const;

export type DocsEnhancementsMap = typeof DOCS_ENHANCEMENTS;
